name: PlatformIO Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Cachea toolchains/paquetes de ~/.platformio para acelerar
      - name: Cache PlatformIO data
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          python -m platformio --version

      - name: Run unit tests (native)
        run: |
          python -m platformio test -e native --verbose
